language: java
sudo: false

install:
  - 

before_script:
 - chmod +x update-coverage.sh

matrix:
  fast_finish: true
  include:
    # unit tests (oraclejdk8)
    - jdk: oraclejdk8
      env: DESC="tests and deploy" CMD="mvn clean integration-test failsafe:verify" COVERAGE_CMD="" DEPLOY="true"

    # checkstyle (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="checkstyle"
        - CMD="mvn clean verify -DskipTests -DskipITs -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true"
        - COVERAGE_CMD=""

    # cobertura and codecov (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="cobertura and codecov"
        - CMD="mvn clean compile cobertura:check cobertura:cobertura"
        - COVERAGE_CMD="bash <(curl -s https://codecov.io/bash)"
        - UPLOAD="true"
    # findbugs and pmd (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="findbugs and pmd"
        - CMD="mvn clean compile pmd:check findbugs:check"
        - COVERAGE_CMD=""

    # site (oraclejdk8 as 'site' success is required to be sure that on release time all will be ok, admins will use oracle8 version)
    - jdk: oraclejdk8
      env:
        - DESC="site"
        - CMD1="mvn clean site -Dlinkcheck.skip=true -DskipTests -DskipITs "
        - CMD2=" -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true -Dcheckstyle.ant.skip=true"
        - CMD=$CMD1$CMD2
        - COVERAGE_CMD=""
    # assembly (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="assembly"
        - CMD1="mvn clean install -Passembly -DskipTests -DskipITs -Dcobertura.skip=true"
        - CMD2=" -Dpmd.skip=true -Dfindbugs.skip=true -Dcheckstyle.ant.skip=true"
        - CMD=$CMD1$CMD2
        - COVERAGE_CMD=""

script: eval $CMD

after_success:
  - eval $COVERAGE_CMD
  - >-
    if [[ $UPLOAD == 'true'
       ]];
    then
      ./update-coverage.sh
    fi
  - >-
    if [[ $TRAVIS_REPO_SLUG == 'checkstyle/checkstyle'
            && $TRAVIS_BRANCH == 'master'
            && $TRAVIS_PULL_REQUEST == 'false'
            && $DEPLOY == 'true'
       ]];
    then
        mvn -s config/deploy-settings.xml deploy \
          -DskipTests -DskipITs -Dpmd.skip=true -Dfindbugs.skip=true \
          -Dcobertura.skip=true -Dcheckstyle.ant.skip=true ;
    fi

cache:
  directories:
  - ~/.m2

env:
  global:
    secure: iIUzcCH0VTNTcNMF/6F9areorYb7378GcyA5HgjWX+c4yucVMYGqW4Oz1DVXx1s2Lgk6w5gNjCXeL/O0X9ilw14x22Rv65uKpbFJOIPriuH7NYvg+pZJzupYlKQwQ/4OKj+EER5jFJT4J828c2Iiia1md9dJBxYZwsomfd2RwfbyKTyz7XKOtiom87jPYnqClbRb0xSBaO47QQOTEQIos7HZP5OG/zhAwApjrt+qDL8Sp8hCxJdPAe5BkdvA3a9aFSFgL2xAnfdXGgUPjKEKZkoeaidycnifH6PKjS5Uh7Y0STS3l3vBYOXoui0s5wvhozDIz0TiM2IUJBrZyqpn7O9x6JzMLskY80jxRFzm+HqDBsUD5MsZ/SLYrteboMgxotgyKRdxsrnWuMMYZTZIZHM4XdGB2b6vbJ1vMh0OYqQxYfan7nUm5DY3LUgoFQ1WHQlQDY1pLGFNiMhoxleM1cPBguuMw9sydbhEaI1V4PkVIk7rn52zUPwKNdIxkJ2MAMzlcJ3D23uG+kDcBPRtrd46Qh5s9PLnwsK4PMoUcTeKVwQdBwb4d9fryZa790HFk0pQFoe4p22LqqkRHUv3rexLdd2Jm1oEmyjoNV/R2RZHV5+0/nfV7afz811PE2R8UKEQpTIXJI/OggSJ2uv/3//fsYhrtZakEHcrwkuKmR4=