language: java
sudo: false

cache:
  directories:
  - ~/.m2

install:
  -

matrix:
  fast_finish: true
  include:
    # NonDex (oraclejdk8)
    - jdk: oraclejdk8
      env: DESC="NonDex" CMD="mvn clean nondex:nondex" COVERAGE_CMD="" DEPLOY="false"


script: eval $CMD

after_success:
  - eval $COVERAGE_CMD
  - >-
    if [[ $TRAVIS_REPO_SLUG == 'checkstyle/checkstyle'
            && $TRAVIS_BRANCH == 'master'
            && $TRAVIS_PULL_REQUEST == 'false'
            && $DEPLOY == 'true'
       ]];
    then
        mvn -s config/deploy-settings.xml deploy \
          -DskipTests -DskipITs -Dpmd.skip=true -Dfindbugs.skip=true \
          -Dcobertura.skip=true -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true -Dxml.skip=true ;
    fi
