language: java
sudo: false

cache:
  directories:
  - ~/.m2

install:
  -

matrix:
  fast_finish: true
  include:
    # unit tests (oraclejdk8)
    - jdk: oraclejdk8
      env: DESC="tests and deploy" CMD="mvn clean integration-test failsafe:verify" COVERAGE_CMD="" DEPLOY="true"

    # checkstyle (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="checkstyle and sevntu-checkstyle"
        - CMD="mvn clean verify -DskipTests -DskipITs -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true"
        - COVERAGE_CMD=""

    # cobertura and codecov (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="cobertura and codecov"
        - CMD="mvn clean compile cobertura:check cobertura:cobertura"
        - COVERAGE_CMD="bash <(curl -s https://codecov.io/bash)"
    # findbugs and pmd (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="findbugs and pmd"
        - CMD="mvn clean compile pmd:check findbugs:check"
        - COVERAGE_CMD=""

    # NoErrorTest - Orekit (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoErrorTest - Orekit"
        - CMD1="mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true "
        - CMD2="              -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD3="              -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true -Dxml.skip=true"
        - CMD4=" && CS_POM_VERSION=$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)"
        - CMD5=" && echo CS_version:\$CS_POM_VERSION"
        - CMD6=" && git clone https://github.com/checkstyle/Orekit.git && cd Orekit"
        - CMD7=" && mvn compile checkstyle:check -Dorekit.checkstyle.version=\$CS_POM_VERSION"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7
        - COVERAGE_CMD=""

    # NoErrorTest - XWiki (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoErrorTest - XWiki"
        - CMD1="mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true"
        - CMD2="              -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD3="              -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true -Dxml.skip=true"
        - CMD4=" && CS_POM_VERSION=$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)"
        - CMD5=" && echo CS_version:\$CS_POM_VERSION"
        - CMD6=" && git clone https://github.com/checkstyle/xwiki-commons/ "
        - CMD7=" && cd xwiki-commons && git checkout checkstyle-regression "
        - CS_CMD="  && mvn install -DskipTests -Dxwiki.clirr.skip=true checkstyle:check -Dcheckstyle.version=\$CS_POM_VERSION"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CS_CMD
        - COVERAGE_CMD=""

    # NoErrorTest - Apache Apex (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoErrorTest - Apache Apex"
        - CMD1="mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true"
        - CMD2="              -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD3="              -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true -Dxml.skip=true"
        - CMD4=" && CS_POM_VERSION=$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)"
        - CMD5=" && echo CS_version:\$CS_POM_VERSION"
        - CMD6=" && git clone https://github.com/apache/incubator-apex-core/ && cd incubator-apex-core"
        - CS_CMD=" && mvn compile checkstyle:check -Dcheckstyle.version=\$CS_POM_VERSION"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CS_CMD
        - COVERAGE_CMD=""

    # NoExceptiontest - Checkstyle, sevntu-checkstyle (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - Checkstyle, sevntu-checkstyle"
        - CMD1="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester "
        - CMD2=" && sed -i.'' 's/^guava/#guava/' projects-for-travis.properties "
        - CMD3=" && sed -i.'' 's/#checkstyle/checkstyle/' projects-for-travis.properties "
        - CMD4=" && sed -i.'' 's/#sevntu-checkstyle/sevntu-checkstyle/' projects-for-travis.properties "
        - CMD5=" && sed -i.'' 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh "
        - CMD6=" && cd ../../ && mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true "
        - CMD7="                  -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD8="                  -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true -Dxml.skip=true"
        - CMD9=" && cd contribution/checkstyle-tester "
        - CMD10=" && ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CMD8$CMD9$CMD10
        - COVERAGE_CMD=""
    # NoExceptiontest - Guava (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - Guava"
        - CMD1="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester"
        - CMD2=" && sed -i.'' 's/^guava/#guava/' projects-for-travis.properties"
        - CMD3=" && sed -i.'' 's/#guava/guava/' projects-for-travis.properties"
        - CMD4=" && sed -i.'' 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh"
        - CMD5=" && cd ../../ && mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true"
        - CMD6="                   -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD7="                   -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true -Dxml.skip=true"
        - CMD8=" && cd contribution/checkstyle-tester "
        - CMD9=" && ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CMD8$CMD9
        - COVERAGE_CMD=""
    # NoExceptiontest - Guava with google_checks (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - Guava with google_checks"
        - CMD1="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester"
        - CMD2=" && sed -i.'' 's/^guava/#guava/' projects-for-travis.properties"
        - CMD3=" && sed -i.'' 's/#guava/guava/' projects-for-travis.properties"
        - CMD4=" && sed -i.'' 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh"
        - CMD5=" && cd ../../ && mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true"
        - CMD6="                   -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD7="                   -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true -Dxml.skip=true"
        - CMD8=" && sed -i.'' 's/warning/ignore/' src/main/resources/google_checks.xml"
        - CMD9=" && cd contribution/checkstyle-tester "
        - CMD10=" && ./launch.sh -Dcheckstyle.config.location=../../src/main/resources/google_checks.xml
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CMD8$CMD9$CMD10
        - COVERAGE_CMD=""
    # NoExceptionTest - Hibernate ORM (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - Hibernate ORM"
        - CMD1="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester "
        - CMD2="&& sed -i.'' 's/^guava/#guava/' projects-for-travis.properties "
        - CMD3="&& sed -i.'' 's/#hibernate-orm/hibernate-orm/' projects-for-travis.properties "
        - CMD4="&& sed -i.'' 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh "
        - CMD5="&& cd ../../ && mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true "
        - CMD6="                  -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD7="                  -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true  -Dxml.skip=true"
        - CMD8="&& cd contribution/checkstyle-tester "
        - CMD9="&& ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CMD8$CMD9
        - COVERAGE_CMD=""
    # NoExceptionTest - FindBugs (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - FindBugs"
        - CMD1="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester "
        - CMD2="&& sed -i.'' 's/^guava/#guava/' projects-for-travis.properties "
        - CMD3="&& sed -i.'' 's/#findbugs/findbugs/' projects-for-travis.properties "
        - CMD4="&& sed -i.'' 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh "
        - CMD5="&& cd ../../ && mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true "
        - CMD6="                  -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD7="                  -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true  -Dxml.skip=true"
        - CMD8="&& cd contribution/checkstyle-tester "
        - CMD9="&& ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CMD8$CMD9
        - COVERAGE_CMD=""
    # NoExceptionTest - Pmd,elasticsearch,lombok-ast (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - Pmd,elasticsearch,lombok-ast"
        - CMD1="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester "
        - CMD2="&& sed -i.'' 's/^guava/#guava/' projects-for-travis.properties "
        - CMD3="&& sed -i.'' 's/#pmd/pmd/' projects-for-travis.properties "
        - CMD4="&& sed -i.'' 's/#elasticsearch/elasticsearch/' projects-for-travis.properties "
        - CMD5="&& sed -i.'' 's/#lombok-ast/lombok-ast/' projects-for-travis.properties "
        - CMD6="&& sed -i.'' 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh "
        - CMD7="&& cd ../../ && mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true "
        - CMD8="                  -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD9="                  -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true  -Dxml.skip=true"
        - CMD10="&& cd contribution/checkstyle-tester "
        - CMD11="&& ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CMD8$CMD9$CMD10$CMD11
        - COVERAGE_CMD=""
    # NoExceptionTest - RxJava,java-design-patterns,MaterialDesignLibrary,apache-ant,apache-jsecurity,android-launcher (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - RxJava,java-design-patterns,MaterialDesignLibrary,apache-ant,apache-jsecurity,android-launcher"
        - CMD01="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester "
        - CMD02="&& sed -i.'' 's/^guava/#guava/' projects-for-travis.properties "
        - CMD03="&& sed -i.'' 's/#RxJava/RxJava/' projects-for-travis.properties "
        - CMD04="&& sed -i.'' 's/#java-design-patterns/java-design-patterns/' projects-for-travis.properties "
        - CMD05="&& sed -i.'' 's/#MaterialDesignLibrary/MaterialDesignLibrary/' projects-for-travis.properties "
        - CMD06="&& sed -i.'' 's/#apache-ant/apache-ant/' projects-for-travis.properties "
        - CMD07="&& sed -i.'' 's/#apache-jsecurity/apache-jsecurity/' projects-for-travis.properties "
        - CMD08="&& sed -i.'' 's/#android-launcher/android-launcher/' projects-for-travis.properties "
        - CMD09="&& sed -i.'' 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh "
        - CMD10="&& cd ../../ && mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true "
        - CMD11="                  -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD12="                  -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true  -Dxml.skip=true"
        - CMD13="&& cd contribution/checkstyle-tester "
        - CMD14="&& ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - CMD=$CMD01$CMD02$CMD03$CMD04$CMD05$CMD06$CMD07$CMD08$CMD09$CMD10$CMD11$CMD12$CMD13$CMD14
        - COVERAGE_CMD=""
    # NoExceptionTest - Spring (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - Spring"
        - CMD1="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester"
        - CMD2=" && sed -i.'' 's/^guava/#guava/' projects-for-travis.properties "
        - CMD3=" && sed -i.'' 's/#spring-framework/spring-framework/' projects-for-travis.properties "
        - CMD4=" && sed -i.'' 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh "
        - CMD5=" && cd ../../ && mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true "
        - CMD6="                   -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD7="                   -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true  -Dxml.skip=true"
        - CMD8=" && cd contribution/checkstyle-tester "
        - CMD9=" && ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CMD8$CMD9
        - COVERAGE_CMD=""
    # NoExceptionTest - Hbase (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - Hbase"
        - CMD1="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester "
        - CMD2="&& sed -i.'' 's/^guava/#guava/' projects-for-travis.properties "
        - CMD3="&& sed -i.'' 's/#Hbase/Hbase/' projects-for-travis.properties "
        - CMD4="&& sed -i.'' 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh "
        - CMD5="&& cd ../../ && mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true "
        - CMD6="                 -Dpmd.skip=true -Dfindbugs.skip=true "
        - CMD7="                 -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true  -Dxml.skip=true"
        - CMD8="&& cd contribution/checkstyle-tester "
        - CMD9="&& ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CMD8$CMD9
        - COVERAGE_CMD=""


script: eval $CMD

after_success:
  - eval $COVERAGE_CMD
  - >-
    if [[ $TRAVIS_REPO_SLUG == 'checkstyle/checkstyle'
            && $TRAVIS_BRANCH == 'master'
            && $TRAVIS_PULL_REQUEST == 'false'
            && $DEPLOY == 'true'
       ]];
    then
        mvn -s config/deploy-settings.xml deploy \
          -DskipTests -DskipITs -Dpmd.skip=true -Dfindbugs.skip=true \
          -Dcobertura.skip=true -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true -Dxml.skip=true ;
    fi
